Accommodate derived files as input resources
When consuming such derived files, pack them into a ZIP archive first
in order to project them all under the same directory tree.

diff --git a/test/diff-test-runner b/test/diff-test-runner
--- a/test/diff-test-runner
+++ b/test/diff-test-runner
@@ -7,7 +7,8 @@ set -e -u -o pipefail
 actual_file=$1
 golden_file=$2
 
-diff_output="$(diff ${golden_file} ${actual_file})"
+# NB: diff fails when there's a difference to report.
+diff_output="$(diff ${golden_file} ${actual_file})" || :
 if [ -n "${diff_output}" ]; then
   echo "FAIL: Actual output differs from expected golden content:"
   echo "${diff_output}"
